In [ ]:
from importlib.resources import path
from operator import is_not
from pathlib import Path
import sys

import pandas as pd

NB_DIR = Path.cwd().resolve()                      # .../reports/jupiter_notebooks
PROJECT_ROOT = NB_DIR.parents[1]                   # .../PracaDyplomowaKozminski
REPORTS_DIR = PROJECT_ROOT / "reports"             # .../PracaDyplomowaKozminski/reports

sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(REPORTS_DIR))

from etl_pipeline.ExtractData import ExtractData
# alternatywnie: from reports.etl_pipeline.ExtractData import ExtractData

data = ExtractData().extract()

In [41]:
data.head()

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,2019-08-05T00:00:00.000,16:30,QUEENS,11434,40.676052,-73.790184,"{'type': 'Point', 'coordinates': [-73.790184, ...",NaN,NaN,150-08 123 AVENUE,...,Unspecified,NaN,NaN,NaN,4184637,Sedan,Pick-up Truck,NaN,NaN,NaN
1,2019-08-27T00:00:00.000,16:02,BROOKLYN,11225,40.657780,-73.951096,"{'type': 'Point', 'coordinates': [-73.951096, ...",NaN,NaN,288 HAWTHORNE STREET,...,Unspecified,NaN,NaN,NaN,4195773,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
2,2019-08-15T00:00:00.000,17:57,MANHATTAN,10002,40.718143,-73.993835,"{'type': 'Point', 'coordinates': [-73.993835, ...",CHRYSTIE STREET,GRAND STREET,NaN,...,NaN,NaN,NaN,NaN,4202457,Sedan,NaN,NaN,NaN,NaN
3,2019-08-30T00:00:00.000,21:53,BRONX,10460,40.840534,-73.866610,"{'type': 'Point', 'coordinates': [-73.86661, 4...",NaN,NaN,1837 EAST TREMONT AVENUE,...,Unspecified,NaN,NaN,NaN,4198749,Taxi,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
4,2019-08-06T00:00:00.000,9:45,MANHATTAN,10016,40.745440,-73.975400,"{'type': 'Point', 'coordinates': [-73.9754, 40...",EAST 35 STREET,2 AVENUE,NaN,...,Driver Inattention/Distraction,NaN,NaN,NaN,4183798,Station Wagon/Sport Utility Vehicle,Bike,NaN,NaN,NaN

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1612178 entries, 0 to 1612177
Data columns (total 29 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   ACCIDENT DATE                  1612178 non-null  object
 1   ACCIDENT TIME                  1612178 non-null  object
 2   BOROUGH                        1127553 non-null  object
 3   ZIP CODE                       1127376 non-null  object
 4   LATITUDE                       1415893 non-null  float64
 5   LONGITUDE                      1415893 non-null  float64
 6   LOCATION                       1415893 non-null  object
 7   ON STREET NAME                 1298002 non-null  object
 8   CROSS STREET NAME              1079193 non-null  object
 9   OFF STREET NAME                219732 non-null   object
 10  NUMBER OF PERSONS INJURED      1612161 non-null  float64
 11  NUMBER OF PERSONS KILLED       1612145 non-null  float64
 12  NUMBER OF PEDESTRIANS INJURED  1612178 non-null  int64
 13  NUMBER OF PEDESTRIANS KILLED   1612178 non-null  int64
 14  NUMBER OF CYCLIST INJURED      1612178 non-null  int64
 15  NUMBER OF CYCLIST KILLED       1612178 non-null  int64
 16  NUMBER OF MOTORIST INJURED     1612178 non-null  int64
 17  NUMBER OF MOTORIST KILLED      1612178 non-null  int64
 18  CONTRIBUTING FACTOR VEHICLE 1  1607854 non-null  object
 19  CONTRIBUTING FACTOR VEHICLE 2  1396127 non-null  object
 20  CONTRIBUTING FACTOR VEHICLE 3  104254 non-null   object
 21  CONTRIBUTING FACTOR VEHICLE 4  21789 non-null    object
 22  CONTRIBUTING FACTOR VEHICLE 5  5622 non-null     object
 23  COLLISION_ID                   1612178 non-null  int64
 24  VEHICLE TYPE CODE 1            1606597 non-null  object
 25  VEHICLE TYPE CODE 2            1346858 non-null  object
 26  VEHICLE TYPE CODE 3            128742 non-null   object
 27  VEHICLE TYPE CODE 4            46009 non-null    object
 28  VEHICLE TYPE CODE 5            10150 non-null    object
dtypes: float64(4), int64(7), object(18)
memory usage: 356.7+ MB

In [43]:
data.describe()

,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,COLLISION_ID
count,1.415893e+06,1.415893e+06,1.612161e+06,1.612145e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06
mean,4.068864e+01,-7.386657e+01,2.631363e-01,1.185998e-03,5.060483e-02,6.302034e-04,2.098590e-02,9.242156e-05,1.916854e-01,4.633483e-04,2.765946e+06
std,1.200403e+00,2.438640e+00,6.584832e-01,3.644859e-02,2.316972e-01,2.577872e-02,1.445222e-01,9.677481e-03,6.206497e-01,2.334547e-02,1.506373e+06
min,0.000000e+00,-2.012371e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.300000e+01
25%,4.066882e+01,-7.397746e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.014464e+06
50%,4.072258e+01,-7.393002e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.422826e+06
75%,4.076789e+01,-7.386727e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.854210e+06
max,4.231832e+01,0.000000e+00,3.100000e+01,8.000000e+00,2.700000e+01,6.000000e+00,4.000000e+00,2.000000e+00,3.100000e+01,5.000000e+00,4.249104e+06

zamiana typow danych

In [44]:
import pandas as pd
data['ACCIDENT DATE'] = data['ACCIDENT DATE'].astype('datetime64[ns]')
data['ACCIDENT TIME'] = pd.to_datetime(data['ACCIDENT TIME'], format='%H:%M')
data['ACCIDENT HOUR'] = data['ACCIDENT TIME'].dt.hour

In [45]:
data['ACCIDENT TIME'] = data['ACCIDENT TIME'].dt.hour

usuwanie zbednych kolumn

sprawdzenie danych

In [46]:
wrong_long = data.loc[data['LOCATION'].notna() & data['LONGITUDE'].isna()]
wrong_lati = data.loc[data['LOCATION'].notna() & data['LATITUDE'].isna()]

# sprawdzenia czy moza wywlaic location

In [47]:
location_test = data[['LATITUDE','LONGITUDE', 'LOCATION']]
location_test.head()

    LATITUDE  LONGITUDE                                           LOCATION
0  40.676052 -73.790184  {'type': 'Point', 'coordinates': [-73.790184, ...
1  40.657780 -73.951096  {'type': 'Point', 'coordinates': [-73.951096, ...
2  40.718143 -73.993835  {'type': 'Point', 'coordinates': [-73.993835, ...
3  40.840534 -73.866610  {'type': 'Point', 'coordinates': [-73.86661, 4...
4  40.745440 -73.975400  {'type': 'Point', 'coordinates': [-73.9754, 40...

In [48]:
location_test['part_LONG'] = location_test['LOCATION'].str.split(",").str[1].str.replace("'coordinates': [", '', regex=False)
location_test['part_LAT'] = location_test['LOCATION'].str.split(",").str[2].str.replace(']}', '', regex=False)
location_test.head()

C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\4125805163.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_test['part_LONG'] = location_test['LOCATION'].str.split(",").str[1].str.replace("'coordinates': [", '', regex=False)
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\4125805163.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_test['part_LAT'] = location_test['LOCATION'].str.split(",").str[2].str.replace(']}', '', regex=False)

,LATITUDE,LONGITUDE,LOCATION,part_LONG,part_LAT
0,40.676052,-73.790184,"{'type': 'Point', 'coordinates': [-73.790184, ...",-73.790184,40.676052
1,40.657780,-73.951096,"{'type': 'Point', 'coordinates': [-73.951096, ...",-73.951096,40.65778
2,40.718143,-73.993835,"{'type': 'Point', 'coordinates': [-73.993835, ...",-73.993835,40.718143
3,40.840534,-73.866610,"{'type': 'Point', 'coordinates': [-73.86661, 4...",-73.86661,40.840534
4,40.745440,-73.975400,"{'type': 'Point', 'coordinates': [-73.9754, 40...",-73.9754,40.74544

In [49]:
location_test['part_LONG'] = location_test['part_LONG'].astype(float)
location_test['part_LAT'] = location_test['part_LAT'].astype(float)
location_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1612178 entries, 0 to 1612177
Data columns (total 5 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   LATITUDE   1415893 non-null  float64
 1   LONGITUDE  1415893 non-null  float64
 2   LOCATION   1415893 non-null  object
 3   part_LONG  1415893 non-null  float64
 4   part_LAT   1415893 non-null  float64
dtypes: float64(4), object(1)
memory usage: 61.5+ MB

C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\1618981983.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_test['part_LONG'] = location_test['part_LONG'].astype(float)
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\1618981983.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location_test['part_LAT'] = location_test['part_LAT'].astype(float)

In [50]:
test_lat = location_test.loc[location_test['LATITUDE'] != location_test['part_LAT']].dropna(subset=['LOCATION'])
test_long = location_test.loc[location_test['LONGITUDE'] != location_test['part_LONG']].dropna(subset=['LOCATION'])

In [51]:
test_long.head()

Empty DataFrame
Columns: [LATITUDE, LONGITUDE, LOCATION, part_LONG, part_LAT]
Index: []

In [52]:
data = data.drop(columns=['LOCATION']) # na pdostaie sprawdzneia danych pinizej

# oznaczenie danych ktore moga byc watlipwej jakosci pod wzgledem ulic

In [53]:
empty_street_without_loc = data.loc[data['ON STREET NAME'].isna() & data['CROSS STREET NAME'].isna() & data['OFF STREET NAME'].isna() & (data['LATITUDE'].isna())]
empty_street_without_loc

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,NUMBER OF PERSONS INJURED,...,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5,ACCIDENT HOUR
79,2016-03-05,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,3400498,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN,19
107,2013-08-27,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,2897534,UNKNOWN,PICK-UP TRUCK,NaN,NaN,NaN,17
3846,2019-08-11,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,4192430,Sedan,Sedan,NaN,NaN,NaN,13
12165,2019-08-04,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,4188099,Sedan,NaN,NaN,NaN,NaN,21
20046,2018-08-30,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,3972359,Carry All,Sedan,NaN,NaN,NaN,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612022,2012-07-08,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,2879036,PASSENGER VEHICLE,NaN,NaN,NaN,NaN,18
1612033,2012-07-21,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,2975671,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN,11
1612047,2012-07-06,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,Unspecified,NaN,NaN,3121380,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,18
1612069,2012-07-12,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,2879041,PASSENGER VEHICLE,UNKNOWN,NaN,NaN,NaN,9
1612106,2012-07-06,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,2912110,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN,11

usuwam przypadki gdzie nie ma zadnje ulicy ani wspolzednych

In [54]:
data['brak_ulicy']=False
data.loc[empty_street_without_loc.index, 'brak_ulicy'] = True

In [55]:
data['brak_wspolrzednych']=False
empty_location = data.loc[((data['LONGITUDE'].isna()) | (data['LATITUDE'].isna())) | ((data['LONGITUDE'] == 0.0) | (data['LATITUDE'] == 0.0))]
data.loc[empty_location.index, 'brak_wspolrzednych'] = True
empty_location

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,NUMBER OF PERSONS INJURED,...,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5,ACCIDENT HOUR,brak_ulicy,brak_wspolrzednych
26,2019-08-02,13,NaN,NaN,NaN,NaN,WESTCHESTER AVENUE,BRUCKNER BOULEVARD,NaN,0.0,...,NaN,4182323,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,13,False,False
35,2019-08-14,17,MANHATTAN,10001,NaN,NaN,WEST 34 STREET,12 AVENUE,NaN,0.0,...,NaN,4189031,Sedan,Sedan,NaN,NaN,NaN,17,False,False
37,2019-08-07,16,NaN,NaN,NaN,NaN,HUTCHINSON RIVER PARKWAY,NaN,NaN,2.0,...,NaN,4185359,Pick-up Truck,NaN,NaN,NaN,NaN,16,False,False
44,2019-08-02,0,NaN,NaN,NaN,NaN,VANWYCK EXPRESSWAY,109 AVENUE,NaN,0.0,...,NaN,4181243,Sedan,Sedan,NaN,NaN,NaN,0,False,False
46,2019-08-15,18,NaN,NaN,NaN,NaN,BROOKLYN BRIDGE,NaN,NaN,0.0,...,NaN,4192999,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,18,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612126,2012-07-11,9,NaN,NaN,NaN,NaN,HILLSIDE AVENUE,KEW GARDENS ROAD,NaN,0.0,...,NaN,203786,TAXI,PASSENGER VEHICLE,NaN,NaN,NaN,9,False,False
1612144,2012-07-22,15,NaN,NaN,NaN,NaN,WEST 14 STREET,10 AVENUE,NaN,0.0,...,NaN,16715,TAXI,PASSENGER VEHICLE,NaN,NaN,NaN,15,False,False
1612157,2012-07-19,8,NaN,NaN,NaN,NaN,VERNON BOULEVARD,50 AVENUE,NaN,0.0,...,NaN,238819,PICK-UP TRUCK,BUS,NaN,NaN,NaN,8,False,False
1612164,2012-07-15,10,NaN,NaN,NaN,NaN,64 STREET,CLINTON AVENUE,NaN,1.0,...,NaN,213321,VAN,PASSENGER VEHICLE,NaN,NaN,NaN,10,False,False
1612174,2012-07-09,16,NaN,NaN,NaN,NaN,EDWARD L GRANT HIGHWAY,WEST 169 STREET,NaN,5.0,...,NaN,85220,PASSENGER VEHICLE,LIVERY VEHICLE,PASSENGER VEHICLE,NaN,NaN,16,False,False

# sprawdzenie dzielnicy

In [56]:
data['brak_dzielnicy']=False
data['brak_kodu']=False
empty_BOROUGH = data.loc[data['BOROUGH'].isna()]
empty_zip_code = data.loc[data['ZIP CODE'].isna()]
data.loc[empty_BOROUGH.index, 'brak_dzielnicy'] = True
data.loc[empty_BOROUGH.index, 'brak_kodu'] = True

In [57]:
uniq_location_and_borough = data[['BOROUGH', 'ZIP CODE', 'LATITUDE', 'LONGITUDE']].loc[data['brak_wspolrzednych']==False].drop_duplicates()
uniq_location_and_borough

               BOROUGH ZIP CODE   LATITUDE  LONGITUDE
0               QUEENS    11434  40.676052 -73.790184
1             BROOKLYN    11225  40.657780 -73.951096
2            MANHATTAN    10002  40.718143 -73.993835
3                BRONX    10460  40.840534 -73.866610
4            MANHATTAN    10016  40.745440 -73.975400
...                ...      ...        ...        ...
1609607         QUEENS    11354  40.771994 -73.829581
1609623  STATEN ISLAND    10304  40.596290 -74.090684
1609666         QUEENS    11363  40.776593 -73.752894
1609772      MANHATTAN    10075  40.775466 -73.964830
1610389         QUEENS    11001  40.736245 -73.702966

[203376 rows x 4 columns]

In [58]:
uniq_location_and_borough_with_all_data = uniq_location_and_borough.loc[uniq_location_and_borough['BOROUGH'].notna()]
uniq_location_and_borough_without_all_data = uniq_location_and_borough.loc[uniq_location_and_borough['BOROUGH'].isna()]
uniq_location_and_borough_with_all_data['row_number'] = uniq_location_and_borough_with_all_data.groupby(['LATITUDE', 'LONGITUDE']).cumcount() + 1
pivot_uniq = uniq_location_and_borough_with_all_data.pivot_table(index=['LATITUDE', 'LONGITUDE'], values='row_number', aggfunc='max')
pivot_uniq_only_1_row_number = pivot_uniq.loc[pivot_uniq['row_number'] == 1]
pivot_uniq_only_1_row_number = pivot_uniq_only_1_row_number.rename(columns={'row_number': 'wartosc_tymczasowa'})
uniq_location_and_borough_with_all_data_add_good_data = uniq_location_and_borough_with_all_data.merge(pivot_uniq_only_1_row_number, how='left', on=['LATITUDE', 'LONGITUDE'])
uniq_location_and_borough_with_all_data_to_merge = uniq_location_and_borough_with_all_data_add_good_data.loc[uniq_location_and_borough_with_all_data_add_good_data['wartosc_tymczasowa'] ==1]

C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\3081241788.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  uniq_location_and_borough_with_all_data['row_number'] = uniq_location_and_borough_with_all_data.groupby(['LATITUDE', 'LONGITUDE']).cumcount() + 1

In [59]:
uniq_location_and_borough_with_all_data_to_merge

,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,row_number,wartosc_tymczasowa
0,QUEENS,11434,40.676052,-73.790184,1,1.0
1,BROOKLYN,11225,40.657780,-73.951096,1,1.0
2,MANHATTAN,10002,40.718143,-73.993835,1,1.0
3,BRONX,10460,40.840534,-73.866610,1,1.0
4,MANHATTAN,10016,40.745440,-73.975400,1,1.0
...,...,...,...,...,...,...
161483,QUEENS,11354,40.771994,-73.829581,1,1.0
161484,STATEN ISLAND,10304,40.596290,-74.090684,1,1.0
161485,QUEENS,11363,40.776593,-73.752894,1,1.0
161486,MANHATTAN,10075,40.775466,-73.964830,1,1.0
161487,QUEENS,11001,40.736245,-73.702966,1,1.0

In [60]:
data = data.merge(uniq_location_and_borough_with_all_data_to_merge, how='left', on=['LATITUDE', 'LONGITUDE'], suffixes=('', '_completed'))

In [61]:

data['uzupelniona_dzielnica'] = False
data['uzupelniony_kod_pocztowy'] = False
data.loc[(data['BOROUGH_completed'].notna() & (data['BOROUGH'].isna())), 'uzupelniona_dzielnica'] = True

In [62]:
data.loc[(data['ZIP CODE_completed'].notna() & (data['ZIP CODE'].isna())), 'uzupelniony_kod_pocztowy'] = True

In [63]:
data

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,NUMBER OF PERSONS INJURED,...,brak_ulicy,brak_wspolrzednych,brak_dzielnicy,brak_kodu,BOROUGH_completed,ZIP CODE_completed,row_number,wartosc_tymczasowa,uzupelniona_dzielnica,uzupelniony_kod_pocztowy
0,2019-08-05,16,QUEENS,11434,40.676052,-73.790184,NaN,NaN,150-08 123 AVENUE,0.0,...,False,False,False,False,QUEENS,11434,1.0,1.0,False,False
1,2019-08-27,16,BROOKLYN,11225,40.657780,-73.951096,NaN,NaN,288 HAWTHORNE STREET,0.0,...,False,False,False,False,BROOKLYN,11225,1.0,1.0,False,False
2,2019-08-15,17,MANHATTAN,10002,40.718143,-73.993835,CHRYSTIE STREET,GRAND STREET,NaN,1.0,...,False,False,False,False,MANHATTAN,10002,1.0,1.0,False,False
3,2019-08-30,21,BRONX,10460,40.840534,-73.866610,NaN,NaN,1837 EAST TREMONT AVENUE,0.0,...,False,False,False,False,BRONX,10460,1.0,1.0,False,False
4,2019-08-06,9,MANHATTAN,10016,40.745440,-73.975400,EAST 35 STREET,2 AVENUE,NaN,1.0,...,False,False,False,False,MANHATTAN,10016,1.0,1.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612173,2012-07-21,22,BROOKLYN,11226,40.651741,-73.965241,PARADE PLACE,CROOKE AVENUE,NaN,0.0,...,False,False,False,False,BROOKLYN,11226,1.0,1.0,False,False
1612174,2012-07-09,16,NaN,NaN,NaN,NaN,EDWARD L GRANT HIGHWAY,WEST 169 STREET,NaN,5.0,...,False,True,True,True,NaN,NaN,NaN,NaN,False,False
1612175,2012-07-09,14,NaN,NaN,40.791492,-73.935763,NaN,NaN,NaN,0.0,...,False,False,True,True,NaN,NaN,NaN,NaN,False,False
1612176,2012-07-18,9,MANHATTAN,10024,40.779479,-73.973573,CENTRAL PARK WEST,WEST 77 STREET,NaN,0.0,...,False,False,False,False,MANHATTAN,10024,1.0,1.0,False,False
1612177,2012-07-12,3,QUEENS,11361,40.762501,-73.782522,39 AVENUE,203 STREET,NaN,0.0,...,False,False,False,False,QUEENS,11361,1.0,1.0,False,False

In [64]:
data.loc[(data['uzupelniona_dzielnica'] == True) & (data['brak_dzielnicy'] == True), 'BOROUGH'] = data['BOROUGH_completed']
data.loc[(data['uzupelniony_kod_pocztowy'] == True) & (data['brak_kodu'] == True), 'ZIP CODE'] = data['ZIP CODE_completed']

# poprawa warrtosci katerogtycznych CONTRIBUTING FACTOR VEHICLE

In [65]:
data['CONTRIBUTING FACTOR VEHICLE 1'] = data['CONTRIBUTING FACTOR VEHICLE 1'].str.upper()
data['CONTRIBUTING FACTOR VEHICLE 2'] = data['CONTRIBUTING FACTOR VEHICLE 2'].str.upper()
data['CONTRIBUTING FACTOR VEHICLE 3'] = data['CONTRIBUTING FACTOR VEHICLE 3'].str.upper()
data['CONTRIBUTING FACTOR VEHICLE 4'] = data['CONTRIBUTING FACTOR VEHICLE 4'].str.upper()
data['CONTRIBUTING FACTOR VEHICLE 5'] = data['CONTRIBUTING FACTOR VEHICLE 5'].str.upper()

In [66]:
data['CONTRIBUTING FACTOR VEHICLE 5'].drop_duplicates().sort_values()

305900                ALCOHOL INVOLVEMENT
1101356                  BRAKES DEFECTIVE
63482      DRIVER INATTENTION/DISTRACTION
185705                DRIVER INEXPERIENCE
520223                    DRUGS (ILLEGAL)
1093470             FAILURE TO KEEP RIGHT
705078      FAILURE TO YIELD RIGHT-OF-WAY
560250                    FATIGUED/DROWSY
556248                        FELL ASLEEP
16334               FOLLOWING TOO CLOSELY
993685                            ILLNESS
98706                  OBSTRUCTION/DEBRIS
895633            OTHER ELECTRONIC DEVICE
11671                     OTHER VEHICULAR
1407486           OUTSIDE CAR DISTRACTION
49657                  PAVEMENT DEFECTIVE
150260                  PAVEMENT SLIPPERY
137872     REACTION TO UNINVOLVED VEHICLE
403230            TIRE FAILURE/INADEQUATE
833929        TRAFFIC CONTROL DISREGARDED
555                          UNSAFE SPEED
65                            UNSPECIFIED
0                                     NaN
Name: CONTRIBUTING FACTOR VEHICLE 5, dtype: object

In [67]:
data.loc[data['CONTRIBUTING FACTOR VEHICLE 1'].isna()]

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,NUMBER OF PERSONS INJURED,...,brak_ulicy,brak_wspolrzednych,brak_dzielnicy,brak_kodu,BOROUGH_completed,ZIP CODE_completed,row_number,wartosc_tymczasowa,uzupelniona_dzielnica,uzupelniony_kod_pocztowy
450,2019-08-09,0,BRONX,10457,40.851032,-73.901730,NaN,NaN,294 EAST BURNSIDE AVENUE,1.0,...,False,False,False,False,BRONX,10457,1.0,1.0,False,False
548,2019-08-10,22,BROOKLYN,11210,40.625730,-73.956400,OCEAN AVENUE,AVENUE J,NaN,2.0,...,False,False,False,False,BROOKLYN,11210,1.0,1.0,False,False
882,2019-08-14,15,BROOKLYN,11221,40.685635,-73.929596,JEFFERSON AVENUE,NaN,NaN,0.0,...,False,False,True,True,BROOKLYN,11221,1.0,1.0,True,True
997,2019-08-07,20,BROOKLYN,11228,40.612736,-74.011720,86 STREET,NaN,NaN,1.0,...,False,False,True,True,BROOKLYN,11228,1.0,1.0,True,True
2020,2019-08-14,2,BROOKLYN,11233,40.669476,-73.919975,HOWARD AVENUE,NaN,NaN,1.0,...,False,False,True,True,BROOKLYN,11233,1.0,1.0,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1516743,2014-02-04,20,NaN,NaN,NaN,NaN,MEEKER AVENUE,MONITOR STREET,NaN,1.0,...,False,True,True,True,NaN,NaN,NaN,NaN,False,False
1517907,2014-02-16,14,NaN,NaN,NaN,NaN,PARK CIRCLE,PROSPECT PARK SOUTHWEST,NaN,0.0,...,False,True,True,True,NaN,NaN,NaN,NaN,False,False
1518123,2014-02-10,13,NaN,NaN,40.767614,-73.949995,NaN,NaN,NaN,0.0,...,False,False,True,True,NaN,NaN,NaN,NaN,False,False
1518659,2014-02-07,23,MANHATTAN,10065,40.766559,-73.962928,3 AVENUE,EAST 67 STREET,NaN,0.0,...,False,False,False,False,MANHATTAN,10065,1.0,1.0,False,False
1519549,2014-02-12,17,MANHATTAN,10010,40.742235,-73.993291,6 AVENUE,WEST 22 STREET,NaN,0.0,...,False,False,False,False,MANHATTAN,10010,1.0,1.0,False,False

In [68]:
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 1']=='80') | (data['CONTRIBUTING FACTOR VEHICLE 1']=='1'), 'CONTRIBUTING FACTOR VEHICLE 1'] = 'UNSPECIFIED'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 1']=='ILLNES') , 'CONTRIBUTING FACTOR VEHICLE 1'] = 'ILLNESS'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 1']=='REACTION TO OTHER UNINVOLVED VEHICLE') , 'CONTRIBUTING FACTOR VEHICLE 1'] = 'REACTION TO UNINVOLVED VEHICLE'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 1'].isna()) , 'CONTRIBUTING FACTOR VEHICLE 1'] = 'EMPTY'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 2']=='80') | (data['CONTRIBUTING FACTOR VEHICLE 2']=='1'), 'CONTRIBUTING FACTOR VEHICLE 2'] = 'UNSPECIFIED'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 2'].isna()) , 'CONTRIBUTING FACTOR VEHICLE 2'] = 'EMPTY'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 2']=='ILLNES') , 'CONTRIBUTING FACTOR VEHICLE 2'] = 'ILLNESS'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 2']=='REACTION TO OTHER UNINVOLVED VEHICLE') , 'CONTRIBUTING FACTOR VEHICLE 2'] = 'REACTION TO UNINVOLVED VEHICLE'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 3']=='80') | (data['CONTRIBUTING FACTOR VEHICLE 3']=='1'), 'CONTRIBUTING FACTOR VEHICLE 3'] = 'UNSPECIFIED'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 3'].isna()) , 'CONTRIBUTING FACTOR VEHICLE 3'] = 'EMPTY'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 3']=='ILLNES') , 'CONTRIBUTING FACTOR VEHICLE 3'] = 'ILLNESS'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 3']=='REACTION TO OTHER UNINVOLVED VEHICLE') , 'CONTRIBUTING FACTOR VEHICLE 3'] = 'REACTION TO UNINVOLVED VEHICLE'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 4'].isna()) , 'CONTRIBUTING FACTOR VEHICLE 4'] = 'EMPTY'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 5'].isna()) , 'CONTRIBUTING FACTOR VEHICLE 5'] = 'EMPTY'

In [69]:
tmp_df = pd.DataFrame()
for i in range (1,6):
    temp=f'CONTRIBUTING FACTOR VEHICLE {i}'
    if i ==1:
        tmp_df[temp] = ''
        tmp_df[temp] = data[temp].drop_duplicates().sort_values()
    else:
        tmp_df = tmp_df.merge(data[temp].drop_duplicates().sort_values(), left_on='CONTRIBUTING FACTOR VEHICLE 1', right_on=temp, how='outer')
tmp_df

,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5
0,ACCELERATOR DEFECTIVE,ACCELERATOR DEFECTIVE,ACCELERATOR DEFECTIVE,NaN,NaN
1,AGGRESSIVE DRIVING/ROAD RAGE,AGGRESSIVE DRIVING/ROAD RAGE,AGGRESSIVE DRIVING/ROAD RAGE,AGGRESSIVE DRIVING/ROAD RAGE,NaN
2,ALCOHOL INVOLVEMENT,ALCOHOL INVOLVEMENT,ALCOHOL INVOLVEMENT,ALCOHOL INVOLVEMENT,ALCOHOL INVOLVEMENT
3,ANIMALS ACTION,ANIMALS ACTION,ANIMALS ACTION,ANIMALS ACTION,NaN
4,BACKING UNSAFELY,BACKING UNSAFELY,BACKING UNSAFELY,BACKING UNSAFELY,NaN
5,BRAKES DEFECTIVE,BRAKES DEFECTIVE,BRAKES DEFECTIVE,BRAKES DEFECTIVE,BRAKES DEFECTIVE
6,CELL PHONE (HAND-HELD),CELL PHONE (HAND-HELD),CELL PHONE (HAND-HELD),NaN,NaN
7,CELL PHONE (HANDS-FREE),CELL PHONE (HANDS-FREE),CELL PHONE (HANDS-FREE),NaN,NaN
8,DRIVER INATTENTION/DISTRACTION,DRIVER INATTENTION/DISTRACTION,DRIVER INATTENTION/DISTRACTION,DRIVER INATTENTION/DISTRACTION,DRIVER INATTENTION/DISTRACTION
9,DRIVER INEXPERIENCE,DRIVER INEXPERIENCE,DRIVER INEXPERIENCE,DRIVER INEXPERIENCE,DRIVER INEXPERIENCE
10,DRIVERLESS/RUNAWAY VEHICLE,DRIVERLESS/RUNAWAY VEHICLE,DRIVERLESS/RUNAWAY VEHICLE,DRIVERLESS/RUNAWAY VEHICLE,NaN
11,DRUGS (ILLEGAL),DRUGS (ILLEGAL),DRUGS (ILLEGAL),DRUGS (ILLEGAL),DRUGS (ILLEGAL)
12,EATING OR DRINKING,EATING OR DRINKING,NaN,NaN,NaN
13,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY
14,FAILURE TO KEEP RIGHT,FAILURE TO KEEP RIGHT,FAILURE TO KEEP RIGHT,FAILURE TO KEEP RIGHT,FAILURE TO KEEP RIGHT
15,FAILURE TO YIELD RIGHT-OF-WAY,FAILURE TO YIELD RIGHT-OF-WAY,FAILURE TO YIELD RIGHT-OF-WAY,FAILURE TO YIELD RIGHT-OF-WAY,FAILURE TO YIELD RIGHT-OF-WAY
16,FATIGUED/DROWSY,FATIGUED/DROWSY,FATIGUED/DROWSY,FATIGUED/DROWSY,FATIGUED/DROWSY
17,FELL ASLEEP,FELL ASLEEP,FELL ASLEEP,FELL ASLEEP,FELL ASLEEP
18,FOLLOWING TOO CLOSELY,FOLLOWING TOO CLOSELY,FOLLOWING TOO CLOSELY,FOLLOWING TOO CLOSELY,FOLLOWING TOO CLOSELY
19,GLARE,GLARE,GLARE,NaN,NaN
20,HEADLIGHTS DEFECTIVE,HEADLIGHTS DEFECTIVE,NaN,NaN,NaN
21,ILLNESS,ILLNESS,ILLNESS,ILLNESS,ILLNESS
22,LANE MARKING IMPROPER/INADEQUATE,LANE MARKING IMPROPER/INADEQUATE,LANE MARKING IMPROPER/INADEQUATE,NaN,NaN
23,LISTENING/USING HEADPHONES,LISTENING/USING HEADPHONES,NaN,NaN,NaN
24,LOST CONSCIOUSNESS,LOST CONSCIOUSNESS,LOST CONSCIOUSNESS,LOST CONSCIOUSNESS,NaN
25,OBSTRUCTION/DEBRIS,OBSTRUCTION/DEBRIS,OBSTRUCTION/DEBRIS,OBSTRUCTION/DEBRIS,OBSTRUCTION/DEBRIS
26,OTHER ELECTRONIC DEVICE,OTHER ELECTRONIC DEVICE,OTHER ELECTRONIC DEVICE,OTHER ELECTRONIC DEVICE,OTHER ELECTRONIC DEVICE
27,OTHER LIGHTING DEFECTS,OTHER LIGHTING DEFECTS,NaN,NaN,NaN
28,OTHER VEHICULAR,OTHER VEHICULAR,OTHER VEHICULAR,OTHER VEHICULAR,OTHER VEHICULAR
29,OUTSIDE CAR DISTRACTION,OUTSIDE CAR DISTRACTION,OUTSIDE CAR DISTRACTION,OUTSIDE CAR DISTRACTION,OUTSIDE CAR DISTRACTION
30,OVERSIZED VEHICLE,OVERSIZED VEHICLE,OVERSIZED VEHICLE,NaN,NaN
31,PASSENGER DISTRACTION,PASSENGER DISTRACTION,PASSENGER DISTRACTION,NaN,NaN
32,PASSING OR LANE USAGE IMPROPER,PASSING OR LANE USAGE IMPROPER,PASSING OR LANE USAGE IMPROPER,PASSING OR LANE USAGE IMPROPER,NaN
33,PASSING TOO CLOSELY,PASSING TOO CLOSELY,PASSING TOO CLOSELY,PASSING TOO CLOSELY,NaN
34,PAVEMENT DEFECTIVE,PAVEMENT DEFECTIVE,PAVEMENT DEFECTIVE,PAVEMENT DEFECTIVE,PAVEMENT DEFECTIVE
35,PAVEMENT SLIPPERY,PAVEMENT SLIPPERY,PAVEMENT SLIPPERY,PAVEMENT SLIPPERY,PAVEMENT SLIPPERY
36,PEDESTRIAN/BICYCLIST/OTHER PEDESTRIAN ERROR/CO...,PEDESTRIAN/BICYCLIST/OTHER PEDESTRIAN ERROR/CO...,PEDESTRIAN/BICYCLIST/OTHER PEDESTRIAN ERROR/CO...,NaN,NaN
37,PHYSICAL DISABILITY,PHYSICAL DISABILITY,PHYSICAL DISABILITY,PHYSICAL DISABILITY,NaN
38,PRESCRIPTION MEDICATION,PRESCRIPTION MEDICATION,PRESCRIPTION MEDICATION,PRESCRIPTION MEDICATION,NaN
39,REACTION TO UNINVOLVED VEHICLE,REACTION TO UNINVOLVED VEHICLE,REACTION TO UNINVOLVED VEHICLE,REACTION TO UNINVOLVED VEHICLE,REACTION TO UNINVOLVED VEHICLE
40,SHOULDERS DEFECTIVE/IMPROPER,SHOULDERS DEFECTIVE/IMPROPER,NaN,NaN,NaN
41,STEERING FAILURE,STEERING FAILURE,STEERING FAILURE,NaN,NaN
42,TEXTING,TEXTING,NaN,NaN,NaN
43,TINTED WINDOWS,TINTED WINDOWS,TINTED WINDOWS,NaN,NaN
44,TIRE FAILURE/INADEQUATE,TIRE FAILURE/INADEQUATE,TIRE FAILURE/INADEQUATE,NaN,TIRE FAILURE/INADEQUATE
45,TOW HITCH DEFECTIVE,TOW HITCH DEFECTIVE,NaN,NaN,NaN
46,TRAFFIC CONTROL DEVICE IMPROPER/NON-WORKING,TRAFFIC CONTROL DEVICE IMPROPER/NON-WORKING,TRAFFIC CONTROL DEVICE IMPROPER/NON-WORKING,TRAFFIC CONTROL DEVICE IMPROPER/NON-WORKING,NaN
47,TRAFFIC CONTROL DISREGARDED,TRAFFIC CONTROL DISREGARDED,TRAFFIC CONTROL DISREGARDED,TRAFFIC CONTROL DISREGARDED,TRAFFIC CONTROL DISREGARDED
48,TURNING IMPROPERLY,TURNING IMPROPERLY,TURNING IMPROPERLY,TURNING IMPROPERLY,NaN
49,UNSAFE LANE CHANGING,UNSAFE LANE CHANGING,UNSAFE LANE CHANGING,UNSAFE LANE CHANGING,NaN
50,UNSAFE SPEED,UNSAFE SPEED,UNSAFE SPEED,UNSAFE SPEED,UNSAFE SPEED
51,UNSPECIFIED,UNSPECIFIED,UNSPECIFIED,UNSPECIFIED,UNSPECIFIED
52,USING ON BOARD NAVIGATION DEVICE,USING ON BOARD NAVIGATION DEVICE,NaN,NaN,NaN
53,VEHICLE VANDALISM,VEHICLE VANDALISM,NaN,NaN,NaN
54,VIEW OBSTRUCTED/LIMITED,VIEW OBSTRUCTED/LIMITED,VIEW OBSTRUCTED/LIMITED,VIEW OBSTRUCTED/LIMITED,NaN
55,WINDSHIELD INADEQUATE,WINDSHIELD INADEQUATE,NaN,WINDSHIELD INADEQUATE,NaN

# poprawa warrtosci katerogtycznych VEHICLE TYPE CODE

In [70]:
# poprawa warrtosci katerogtycznych CONTRIBUTING FACTOR VEHICLE
data['VEHICLE TYPE CODE 1'] = data['VEHICLE TYPE CODE 1'].str.upper()
data['VEHICLE TYPE CODE 2'] = data['VEHICLE TYPE CODE 2'].str.upper()
data['VEHICLE TYPE CODE 3'] = data['VEHICLE TYPE CODE 3'].str.upper()
data['VEHICLE TYPE CODE 4'] = data['VEHICLE TYPE CODE 4'].str.upper()
data['VEHICLE TYPE CODE 5'] = data['VEHICLE TYPE CODE 5'].str.upper()

In [71]:
test = data.pivot_table(index=['VEHICLE TYPE CODE 2'], aggfunc='count', values='COLLISION_ID')
test

                     COLLISION_ID
VEHICLE TYPE CODE 2
00                              1
1                               1
11 PA                           1
12 PA                           1
15 PA                           1
...                           ...
WESCO                           2
WHEEL                           1
WHITE                          10
WORK                            4
YELLO                           4

[440 rows x 1 columns]

In [72]:
list_to_change_unkonw =[ '00',
 '11 PA',
 '16M',
 '18 WH',
 '2 DOO',
 '2 HOR',
 '2TON',
 '3-WHE',
 '3DC-',
 '4DR',
 '52? T',
 '72000',
 '994',
 'ALUMI',
 'ANBUL',
 'APURP',
 'ART M',
 'ASPHA',
 'AXO',
 'B5-44',
 'BED',
 'BLOCK',
 'BOB C',
 'BOOML',
 'BROOM',
 'BROWN',
 'BUMP',
 'C0MME',
 'CAMPE',
 'CAR C',
 'CARRI',
 'CASE',
 'CAT',
 'CAT 3',
 'CAT 4',
 'CAT32',
 'CB534',
 'CHEVR',
 'CHURC',
 'COMPA',
 'CONTA',
 'CRWZK',
 'D',
 'D1',
 'DELV.',
 'DEPAR',
 'DETAC',
 'DIG-I',
 'DIRTB',
 'DOT #',
 'DSNY',
 'E',
 'E PAS',
 'E-350',
 'E-SKA',
 'E250',
 'E3',
 'E350',
 'EB',
 'EMS',
 'EMT',
 'EXPRE',
 'FARM',
 'FD LA',
 'FLTRL',
 'FORTL',
 'FRE T',
 'FRIEG',
 'G OMR',
 'G PAS',
 'G SEM',
 'G TOW',
 'GARAB',
 'GAS S',
 'GAS T',
 'GLBEN',
 'GMC V',
 'GOLF',
 'GOV V',
 'GOV\'T',
 'HARVE',
 'HI-LO',
 'HIGHL',
 'HOE-L',
 'HOOK',
 'HOTDO',
 'HOUSE',
 'JCB40',
 'JLG B',
 'JLG L',
 'JOHND',
 'LAUND',
 'LG',
 'LL',
 'MAN L',
 'MECHA',
 'MINIV',
 'MO-PE',
 'MOPEN',
 'MOPET',
 'MV',
 'N/A',
 'NA',
 'NEW Y',
 'NV CA',
 'NV150',
 'NYC',
 'NYFD',
 'OFF R',
 'OLM',
 'OML/',
 'OP',
 'PALLE',
 'PASS',
 'PAVIN',
 'PCH',
 'PEDIC',
 'PISH',
 'PLOW',
 'POST',
 'PUMPE',
 'PUSH',
 'RAM',
 'RAZOR',
 'RD/S',
 'RED,',
 'RGS',
 'ROADS',
 'S/SP',
 'SAFET',
 'SBN',
 'SCAFF',
 'SCAVA',
 'SCHOOL BUS',
 'SELF-',
 'SHCOO',
 'SKID',
 'SMALL',
 'SPEC-',
 'SUDAN',
 'SWT',
 'T650',
 'TAN P',
 'TCR',
 'TKP',
 'TL TR',
 'TLR',
 'TOUR',
 'TOWER',
 'TOWIN',
 'TRA/R',
 'TRAIN',
 'TRASH',
 'TRIAL',
 'TRIM',
 'TRT',
 'TUGGE',
 'U HAU',
 'U-TRU',
 'UBER',
 'UD',
 'ULITI',
 'UNK,',
 'UNNKO',
 'US MA',
 'UTLIT',
 'UTLL',
 'VAN A',
 'VAN C',
 'VAN F',
 'VAN W',
 'VAN/B',
 'VMS T',
 'WASTE',
 'WC',
 'WESCO',
 '(CEME',
 '1',
 '12 PA',
 '15 PA',
 '2 TON',
 '2015',
 '3 WHE',
 '3-DOOR',
 '35 FT',
 '3D',
 '4 RUN',
 '4D',
 '4DS',
 '4DSD',
 '985',
 'A',
 'ACCES',
 'APORT',
 'APPOR',
 'AR',
 'ARMOR',
 'ARMY',
 'ATTAC',
 'BA',
 'BACK',
 'BACKH',
 'BARRI',
 'BED T',
 'BOBCA',
 'BOOM',
 'BR',
 'BS',
 'C1',
 'C3',
 'CAB',
 'CAMP',
 'CARGO',
 'CAT 9',
 'CAT P',
 'CAT.',
 'CATE',
 'CATER',
 'CB',
 'CEMEN',
 'CHEVO',
 'CHEVY',
 'CITY',
 'CM',
 'CMIX',
 'CMS-T',
 'CO',
 'COM',
 'COM T',
 'COM.',
 'COMB',
 'COMER',
 'COMIX',
 'COMM',
 'COMME',
 'COMMM',
 'CONST',
 'COURI',
 'CRANE',
 'CUSHM',
 'DP',
 'DUNBA',
 'E - B',
 'E AMB',
 'E BIK',
 'E ONE',
 'E SCO',
 'E- BI',
 'E.M.S',
 'E/BIK',
 'E450',
 'EBIKE',
 'ECONO',
 'ELEC.',
 'ELECT',
 'EMRGN',
 'EMS A',
 'EMS B',
 'EMS H',
 'EN',
 'ENCLOSED BODY - NONREMOVABLE ENCLOSURE',
 'ENCLOSED BODY - REMOVABLE ENCLOSURE',
 'ENGIN',
 'EPO',
 'ESU T',
 'EXCAV',
 'F550',
 'FD FI',
 'FED E',
 'FEDER',
 'FEDEX',
 'FOOD',
 'FORD',
 'FORK',
 'FORK-',
 'FORKL',
 'FR',
 'FREE',
 'FREIG',
 'FRHT',
 'FRONT',
 'FR`',
 'FUEL',
 'G COM',
 'G SPC',
 'GATOR',
 'GE/SC',
 'GEICO',
 'GOKAR',
 'GOVER',
 'GR',
 'GRAIN',
 'GRAY',
 'GRUMM',
 'HAND',
 'HEAVY',
 'HELP',
 'HI TA',
 'HINO',
 'HO',
 'HOPPER',
 'HORSE',
 'HRSE',
 'HUMME',
 'HWY C',
 'ICE C',
 'ICECR',
 'INTER',
 'IP',
 'JEEP',
 'JOHN',
 'KENWO',
 'KUBOT',
 'L1',
 'LD',
 'LF',
 'LIEBH',
 'LIFT',
 'LIFT BOOM',
 'LIGHT',
 'LIMO',
 'LIMOU',
 'LIVESTOCK RACK',
 'LOADE',
 'LOG',
 'LP',
 'LTR',
 'LTRL',
 'LUNCH WAGON',
 'LW',
 'MAC T',
 'MACK',
 'MAIL',
 'MARK',
 'MARKE',
 'MB',
 'MC',
 'MCY B',
 'MD',
 'ME/BE',
 'MH',
 'MINI',
 'MINIBIKE',
 'MINICYCLE',
 'MK',
 'MOBIL',
 'MOPAD',
 'MOVIN',
 'MS',
 'MTA',
 'MTA B',
 'MTA C',
 'MTR S',
 'MULTI-WHEELED VEHICLE',
 'NAVIG',
 'NISSA',
 'NONE',
 'NS AM',
 'NYC A',
 'NYC B',
 'NYC D',
 'NYC F',
 'NYC M',
 'NYCHA',
 'NYPD',
 'NYS A',
 'OIL T',
 'OLC',
 'OML',
 'OMNI',
 'OMNIB',
 'OMR',
 'OMT',
 'OPEN BODY',
 'OTHER',
 'P/SH',
 'PALLET',
 'PARCE',
 'PAS',
 'PAYLO',
 'PC',
 'PEDICAB',
 'PK',
 'PKUP',
 'PL',
 'PM',
 'POIS',
 'POLIC',
 'POSTA',
 'POSTO',
 'POWER',
 'PRKS',
 'PSD',
 'PSH',
 'PSR',
 'PU',
 'PUMP',
 'R/V',
 'R/V C',
 'RANGE',
 'RED T',
 'REFG',
 'RENTA',
 'REP',
 'REPAI',
 'RESCU',
 'RF',
 'RMB',
 'RMP',
 'RMP V',
 'ROAD',
 'RV',
 'RYDER',
 'SANIT',
 'SANTA',
 'SANTI',
 'SCISS',
 'SELF',
 'SEMI',
 'SEMI-',
 'SGWS',
 'SKATE',
 'SKID-',
 'SMART',
 'SNOW',
 'SNOW PLOW',
 'SP',
 'SPC',
 'SPC P',
 'SPEC',
 'SPRIN',
 'SS',
 'ST',
 'ST150',
 'STAK',
 'STAKE OR RACK',
 'STATE',
 'STREE',
 'SUB',
 'SUBN',
 'SUBN/',
 'SUBUR',
 'SUV',
 'SW',
 'SWEEP',
 'TCN',
 'TRC',
 'TRK',
 'TRL',
 'TRLPM',
 'TRLR',
 'U-HAU',
 'U.S.',
 'UHAUL',
 'UHUAL',
 'UKN',
 'ULILI',
 'UNK',
 'UNKNO',
 'UNKNOWN',
 'UNKOW',
 'UPS T',
 'US PO',
 'USP M',
 'USPOS',
 'USPS',
 'USPS2',
 'UT',
 'UTIL',
 'UTILI',
 'VANG',
 'VC',
 'VERIZ',
 'VESPA',
 'VT',
 'WAGON',
 'WD',
 'WELL DRILLER',
 'WHBL',
 'WHEEL',
 'WHITE',
 'WINEB',
 'WINNE',
 'WORK',
 'YELLO',
 '\x7fOMM',
 'Ï¿½MBU',
                          'BUCKE',
 'BUDGE',
 'BULK AGRICULTURE',
 'BULLD',
 'CONT',
 'DEMA-',
 'DEPT',
 'DIESE',
 'DIRT',
 'DOT R',
 'DOT T',
 'FD TR',
 'FLAT',
 'FLAT/',
 'MOTER',
 'MOTOR',
 'MOTOR HOME',
 'MOTORBIKE',
 'MOTORIZED HOME',
 'TE',
 'TF',
 'TN',
 'TR',
 'TRAC',
 'TRAC.',
 'TRACK',
 'TRACT',
 'TRAFF',
 'TRAM',
 'TRANS',
 'VOL',

]

In [73]:
data['VEHICLE TYPE CODE 1'].loc[data['VEHICLE TYPE CODE 1'].isin(list_to_change_unkonw)] = 'UNKNOWN'
data['VEHICLE TYPE CODE 2'].loc[data['VEHICLE TYPE CODE 2'].isin(list_to_change_unkonw)] = 'UNKNOWN'
data['VEHICLE TYPE CODE 3'].loc[data['VEHICLE TYPE CODE 3'].isin(list_to_change_unkonw)] = 'UNKNOWN'
data['VEHICLE TYPE CODE 4'].loc[data['VEHICLE TYPE CODE 4'].isin(list_to_change_unkonw)] = 'UNKNOWN'
data['VEHICLE TYPE CODE 5'].loc[data['VEHICLE TYPE CODE 5'].isin(list_to_change_unkonw)] = 'UNKNOWN'

C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\1237675388.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['VEHICLE TYPE CODE 1'].loc[data['VEHICLE TYPE CODE 1'].isin(list_to_change_unkonw)] = 'UNKNOWN'
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\1237675388.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['VEHICLE TYPE CODE 1'].loc[data['VEHICLE TYPE CODE 1'].isin(list_to_change_unkonw)] = 'UNKNOWN'
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\1237675388.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['VEHICLE TYPE CODE 2'].loc[data['VEHICLE TYPE CODE 2'].isin(list_to_change_unkonw)] = 'UNKNOWN'
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\1237675388.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['VEHICLE TYPE CODE 2'].loc[data['VEHICLE TYPE CODE 2'].isin(list_to_change_unkonw)] = 'UNKNOWN'
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\1237675388.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['VEHICLE TYPE CODE 3'].loc[data['VEHICLE TYPE CODE 3'].isin(list_to_change_unkonw)] = 'UNKNOWN'
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\1237675388.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['VEHICLE TYPE CODE 3'].loc[data['VEHICLE TYPE CODE 3'].isin(list_to_change_unkonw)] = 'UNKNOWN'
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\1237675388.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['VEHICLE TYPE CODE 4'].loc[data['VEHICLE TYPE CODE 4'].isin(list_to_change_unkonw)] = 'UNKNOWN'
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\1237675388.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['VEHICLE TYPE CODE 4'].loc[data['VEHICLE TYPE CODE 4'].isin(list_to_change_unkonw)] = 'UNKNOWN'
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\1237675388.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['VEHICLE TYPE CODE 5'].loc[data['VEHICLE TYPE CODE 5'].isin(list_to_change_unkonw)] = 'UNKNOWN'
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\1237675388.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['VEHICLE TYPE CODE 5'].loc[data['VEHICLE TYPE CODE 5'].isin(list_to_change_unkonw)] = 'UNKNOWN'

In [74]:
DICT_TO_REPLACE = {	 'SEDAN':[ '2 DR SEDAN', '4 DR SEDAN', 'SE', 'SEA',],	 'AMBULANCE':[ 'AM', 'AMABU', 'AMB', 'AMBU', 'AMBUL',],	 'BICYCLE':[ 'BICYC', 'BIKE', 'BK',],	 'BOX TRUCK':[ 'BOX', 'BOX T', 'BOXTR',],	 'CONCRETE MIXER':[ 'CONCR',],	 'CONVERTIBLE':[ 'CONV', 'CONVE',],	 'DELIVERY':[ 'DEL', 'DELIV', 'DELV', 'DELVI',],	 'DUMP':[ 'DUMPS', 'DUMPT',],	 'FIRE TRUCK':[ 'FD NY', 'FDNY', 'FIRE', 'FIRET',],	 'FLAT BED':[ 'FLATB',],	 'GARBAGE OR REFUSE':[ 'GARBA',],	 'LARGE COM VEH(6 OR MORE TIRES)':[ 'LADDE',],	 'LIVERY VEHICLE':[ 'LIVER',],	 'MOPED':[ 'MOPD',],	 'PASSENGER VEHICLE':[ 'PASSA', 'PASSE',],	 'PICK-UP TRUCK':[ 'PICK', 'PICK-', 'PICKU',],	 'REFRIGERATED VAN':[ 'REFRI',],	 'SCHOOL BUS':[ 'SCHOO',],	 'SCOOTER':[ 'SCOO', 'SCOOT',],	 'TANKER':[ 'TANK', 'TANKE',],	 'TOW TRUCK / WRECKER':[ 'TOW', 'TOW T', 'TOW TRUCK', 'TOW-T', 'TOWTR',],	 'VAN':[ 'VAB', 'VAN (', 'VAN CAMPER', 'VAN T', 'VAN/T', 'VANETTE',]	}

In [75]:
for i, j in DICT_TO_REPLACE.items():
    for z in range(1,6):
        data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i

C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i
C:\Users\piotr\AppData\Local\Temp\ipykernel_119896\2565441866.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i

In [76]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1612178 entries, 0 to 1612177
Data columns (total 39 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   ACCIDENT DATE                  1612178 non-null  datetime64[ns]
 1   ACCIDENT TIME                  1612178 non-null  int32
 2   BOROUGH                        1242963 non-null  object
 3   ZIP CODE                       1242748 non-null  object
 4   LATITUDE                       1415893 non-null  float64
 5   LONGITUDE                      1415893 non-null  float64
 6   ON STREET NAME                 1298002 non-null  object
 7   CROSS STREET NAME              1079193 non-null  object
 8   OFF STREET NAME                219732 non-null   object
 9   NUMBER OF PERSONS INJURED      1612161 non-null  float64
 10  NUMBER OF PERSONS KILLED       1612145 non-null  float64
 11  NUMBER OF PEDESTRIANS INJURED  1612178 non-null  int64
 12  NUMBER OF PEDESTRIANS KILLED   1612178 non-null  int64
 13  NUMBER OF CYCLIST INJURED      1612178 non-null  int64
 14  NUMBER OF CYCLIST KILLED       1612178 non-null  int64
 15  NUMBER OF MOTORIST INJURED     1612178 non-null  int64
 16  NUMBER OF MOTORIST KILLED      1612178 non-null  int64
 17  CONTRIBUTING FACTOR VEHICLE 1  1612178 non-null  object
 18  CONTRIBUTING FACTOR VEHICLE 2  1612178 non-null  object
 19  CONTRIBUTING FACTOR VEHICLE 3  1612178 non-null  object
 20  CONTRIBUTING FACTOR VEHICLE 4  1612178 non-null  object
 21  CONTRIBUTING FACTOR VEHICLE 5  1612178 non-null  object
 22  COLLISION_ID                   1612178 non-null  int64
 23  VEHICLE TYPE CODE 1            1606597 non-null  object
 24  VEHICLE TYPE CODE 2            1346858 non-null  object
 25  VEHICLE TYPE CODE 3            128742 non-null   object
 26  VEHICLE TYPE CODE 4            46009 non-null    object
 27  VEHICLE TYPE CODE 5            10150 non-null    object
 28  ACCIDENT HOUR                  1612178 non-null  int32
 29  brak_ulicy                     1612178 non-null  bool
 30  brak_wspolrzednych             1612178 non-null  bool
 31  brak_dzielnicy                 1612178 non-null  bool
 32  brak_kodu                      1612178 non-null  bool
 33  BOROUGH_completed              1194765 non-null  object
 34  ZIP CODE_completed             1194620 non-null  object
 35  row_number                     1194765 non-null  float64
 36  wartosc_tymczasowa             1194765 non-null  float64
 37  uzupelniona_dzielnica          1612178 non-null  bool
 38  uzupelniony_kod_pocztowy       1612178 non-null  bool
dtypes: bool(6), datetime64[ns](1), float64(6), int32(2), int64(7), object(17)
memory usage: 402.8+ MB

# ZAPISUJE NA KONIEC DO CSV

In [77]:
import os
path_to_save = os.path.join(os.getcwd(), '..','..','data_ingestion\\data_clean.csv')
data.to_csv(path_to_save)